DROP TABLE IF EXISTS order_detail;

DROP TABLE IF EXISTS order_data;

DROP TABLE IF EXISTS order_status;

DROP TABLE IF EXISTS coupun;

DROP TABLE IF EXISTS product;

DROP TABLE IF EXISTS product_category;

DROP TABLE IF EXISTS user_info;

DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS user_role;