package response

const (
	RESPONSE_SUCCESS_MESSAGE               string = "SUCCESS"
	RESPONSE_ERROR_VALIDATION_MESSAGE      string = "VALIDATION_ERROR"
	RESPONSE_ERROR_BUSINESS_LOGIC_MESSAGE  string = "BUSINESS_LOGIC_ERROR"
	RESPONSE_ERROR_UNAUTHORIZED_MESSAGE    string = "UNAUTHORIZED_ERROR"
	RESPONSE_ERROR_DATA_NOT_EXISTS_MESSAGE string = "DATA_NOT_EXISTS_ERROR"
	RESPONSE_ERROR_DUPLICATE_DATA_MESSAGE  string = "DUPLICATE_DATA_ERROR"
	RESPONSE_ERROR_RUNTIME_MESSAGE         string = "RUNTIME_ERROR"
)